name: Package and release

on:
  push:
    tags:
      - '**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Hack around https://github.com/actions/checkout/issues/290
        run: |
          git fetch --tags --force

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"
          annotate: warning
          
      - name: Update Curseforge Translations
        run: ./cf_localizations.sh
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}

      - name: Generate Changelog
        run: ./generate_changelog.sh

      - name: Package and release
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
        with:
          args: -g cata -n "{package-name}-{project-version}"
